# Generated by Django 5.1.6 on 2025-04-26 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_journey",
                to="station.route",
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="train_journey",
                to="station.train",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "destination")},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("cargo", "seat")},
        ),
        migrations.AddConstraint(
            model_name="journey",
            constraint=models.UniqueConstraint(
                fields=("route", "train"), name="unique_route_train"
            ),
        ),
    ]
