# Generated by Django 5.1.6 on 2025-04-26 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_alter_journey_route_alter_journey_train_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_tickets",
                to="station.order",
            ),
        ),
    ]
