# Generated by Django 5.1.6 on 2025-04-26 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0004_order_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ticket",
            name="journey",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="station.journey",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="station.order",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("cargo", "seat", "journey")},
        ),
    ]
