# Generated by Django 5.1.6 on 2025-04-27 13:49

import django.core.validators
import django.db.models.deletion
import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0006_alter_route_distance_alter_station_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={"ordering": ["-departure_time"]},
        ),
        migrations.RemoveConstraint(
            model_name="journey",
            name="unique_route_train",
        ),
        migrations.RemoveConstraint(
            model_name="traintype",
            name="unique_name",
        ),
        migrations.AddField(
            model_name="journey",
            name="crews",
            field=models.ManyToManyField(related_name="journeys", to="station.crew"),
        ),
        migrations.AlterField(
            model_name="crew",
            name="first_name",
            field=models.CharField(
                max_length=255, validators=[station.models.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="crew",
            name="last_name",
            field=models.CharField(
                max_length=255, validators=[station.models.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="latitude",
            field=models.FloatField(validators=[station.models.validate_latitude]),
        ),
        migrations.AlterField(
            model_name="station",
            name="longitude",
            field=models.FloatField(validators=[station.models.validate_latitude]),
        ),
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="cargo_num",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(500),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="places_in_cargo",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(500),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="train_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trains",
                to="station.traintype",
            ),
        ),
        migrations.AlterField(
            model_name="traintype",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, validators=[station.models.validate_name]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journey",
            unique_together={("route", "train")},
        ),
    ]
