# Generated by Django 5.1.6 on 2025-04-27 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0007_alter_journey_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="journey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="station.journey",
            ),
        ),
    ]
